program ::= stmt*
stmt ::= expr ';' | var_decl | reassign | func_def

func_def ::= 'let' ident '(' params ')' '=' expr ';'
params ::= ident (',' ident)*

var_decl ::= 'let' ident '=' expr ';'
reassign ::= 'set' ident '=' expr ';'

func_call ::= ident '(' args ')'
args ::= expr (',' expr)*

expr ::= eql
eql ::= rel ('=' rel | '~=' rel)*
rel ::= add ('<' add | '<=' add | '>' add | '>=' add)*
add ::= unary ('+' mul | '-' mul)*
unary ::= '-'? mul
mul ::= primary ('*' primary | '/' primary)*
primary ::= number | ident | '(' expr ')' | func_call